### ISSUE TITLE
Possibility to edit / move entities

### ISSUE THREAD

**Issue by tracim** [lovasoa/whitebophir#10]
Currently: if I want to modify an entity, I must delete the current one and create a new one. It's ok for basic entities, but as soon as my schema is made of several entities, it will be complicated.

Expected: allow to modify an entity. The minimum would be to be able to move an entity.

This would be a required feature for us to integrate the tool in tracim as a dedicated app

**Comment by lovasoa** [comment]
This is a good feature idea!

**Comment by gsutay** [comment]
Hi Ophir,

Can we collaborate on this? My goal is to complete this feature in 1 week.  Starting today, I can put about 40 hours into this effort. I am familiar with JavaScript and understand the WBO architecture diagram but I am new to WBO development and working with websockets/memory.

This is 2 features to me (edit and move). My objective is to be able to select and move board objects.

I am thinking we select objects now with mouse pointer for delete.  Starting with same object selection, maybe we can assign object to mouse pointer location (instead of deleting) until mouse clicked again. This would provide a select object > drag and drop result.

Let me know what you think.

Cheers,
Gene

**Comment by lovasoa** [comment]
Hello @gsutay,
  It is great to see someone ready to work on this ! Of course, I am ready to help and give guidance. Do not hesitate to open new issues as you start working on the code. 

  More specifically, about the implementation you propose : 
  - Currently, the eraser works by listening to `mouseover` events on the SVG elements on the board. This makes it difficult to erase small object, and I have plans to change that : https://github.com/lovasoa/whitebophir/issues/8 . I don't think object selection should work this way.
 - An idea I had is that object selection could work by creating an SVG rectangle which would both give visual feedback about the selection, and get the list of selected elements using an [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

Do not hesitate to open a PR even before you have something working, so that we can discuss your code as soon as possible.

Thanks for your commitment !

P.S. By the way, out of curiosity, what are you using wbo for ?

**Comment by gsutay** [comment]
@lovasoa

Thanks for the quick reply. I am reading up on the related technologies currently.

My use case would be for meetings, to replace a physical whiteboard with a virtual board where people can select board elements and then move them around (as is done in SAFe training sessions with sticky notes on a physical whiteboard).  Some of the commercial boards I have looked at have this feature already.

Will share once I have some progress on POC to show.

**Comment by gsutay** [comment]
@lovasoa

Thanks for the quick reply. I am reading up on the related technologies currently.

My use case would be for meetings, to replace a physical whiteboard with a virtual board where people can select board elements and then move them around (as is done in SAFe training sessions with sticky notes on a physical whiteboard).  Some of the commercial boards I have looked at have this feature already.

Will share once I have some progress on POC to show.

**Comment by lovasoa** [comment]
@gsutay : You posted the same message twice... Have you done any progress? Do you need help?

**Comment by gsutay** [comment]
I do need help, just emailed you at ophir.lojkine@free.fr.  Is that a good
email for you?

**Comment by lovasoa** [comment]
I'd rather keep this discussion public. Can I paste the email you sent here?

**Comment by gsutay** [comment]
Sure, no problem. I wasn't sure if the issue forum was the right place.

**Comment by lovasoa** [comment]
> Hi @lovasoa ,
> I'm trying to make the text tool look like a sticky note. I have tried adding a background color and image to the tools/text/text.css but this did not work.
> Do you have any suggestions on how I might apply a background color or background image behind the textField created in the tools/text/text.js?


Yes, you can do that in the text tool's CSS. Keep in mind that you are styling an svg element, not an html element. Can you publish your code here on GitHub so that we can see what you are doing?

> On a different note, I am making progress on moving text elements. I goal is to introduce a "Sticky Note" tool as a movable textField with a background.

Are you not working on a tool to select and move elements independently of their size anymore ? This was what I was hoping you could add to wbo. 

Anyway, can you please publish your fork on GitHub so that your work on it is public? If you open a pull request even when your work is still incomplete, then other people may be able to help you, and we can discuss about concrete code.

**Comment by lovasoa** [comment]
This is now implemented as a secondary function of the hand tool.
Feel free to give your feedback and to propose refinements as new issues and pull requests.
