### ISSUE TITLE
Lack in documentation

### ISSUE THREAD

**Issue by petrk94** [lovasoa/whitebophir#19]
Hello,
I really like it, but I facing the problem, that there is no installation guide in the readme.
How does the data get stored? How to delete the whiteboards once created?
Is there an API can access to make changes.
There is just a docker file, but no explanation what it does or how to work with it etc.

Hope you can give me some more information, if you dont have time to update the manual, I can write a short text which can be improved, so at least its saved here.
Thanks

**Comment by lovasoa** [comment]
Oh, yes, I would love a contribution to the documentation !

Here are the answers to your questions: 

#### How does the data get stored?
The data is stored in json files (one file per board) in the `server-data` directory

#### How to delete the whiteboards once created ?
This is currently not possible, on purpose: since there is no user permissions, we don't want a single person to be able to delete the whole whiteboard.
If you have access to the server, you can simply delete the board's json file in `server-data/`.

#### Is there an API can access to make changes ?
The communication protocol is [socket.io](https://socket.io/), it is quite simple, but I haven't documented it. The messages are simple json messages in the form : 

```json
{
    "board": "board name",
    "data": ...
}
```

And the data is specific to each tool. For instance, for a rectangle, it is : 

```json
{
    "type": "rect",
    "id": "unique id",
    "color": "#71AF32",
    "size": 3,
    "opacity": 0.3,
    "x": x,
    "y": y,
    "x2": x,
    "y2": y
}

```


If you have more questions, let me know ! If you want to contribute, you are very welcome !

**Comment by fineman** [comment]
So am I right in thinking to deploy this to our own server we should clone the rep, then build a docker image and deploy that to a container? Linux presumably? Happy to contribute some notes on how to do that if I get a few pointers - new to Docker.

**Comment by lovasoa** [comment]
I should be really simple, when using docker compose.

#### Clone the repository

```
git clone git@github.com:lovasoa/whitebophir.git
cd whitebophir
```

## Running the code in a container (safer)

#### Choose where to persist the data (optional)
You can edit `docker-compose.yml`to choose where you want to persist the data

```yml
    volumes:
      - /home/ophir/whitebophir/server-data:/opt/app/server-data
```

Here, I chose to persist the data in the directory where I cloned the repo

#### Start the service

```
sudo docker-compose up
```

This will start wbo on port 80.

**Comment by lovasoa** [comment]
## Running the code without a container

You can alternatively run the code with node directly, without docker : 

```
npm install
npm start
```

**Comment by lovasoa** [comment]
I also pushed the WBO docker image on docker hub for easier usage:
https://hub.docker.com/repository/docker/lovasoa/wbo

**Comment by lovasoa** [comment]
@petrk94 I would love if you could give feedback on the documentation I wrote [in the README](https://github.com/lovasoa/whitebophir/blob/master/README.md). If you see possible improvements, do not hesitate to suggest them !
