### ISSUE TITLE
Any simpler way to make it responsive for mobile and tablet devices?

### ISSUE THREAD

**Issue by ravi0402** [lovasoa/whitebophir#83]
Right now while drawing something from desktops and listening that event on mobile devices, only 1/4th(approx) part of what we drew on desktop is being shown on mobile.

**Comment by lovasoa** [comment]
Hello ! I'm not sure I understand the issue... The board is infinite, so you see only a small part of it at a time, whatever the size of your viewport. You can always scroll to see the rest of the board. Or are you talking about something else completely ? Can you give a more detailed explanation (with screenshots maybe) of what your problem is ?

**Comment by ctoibvira** [comment]
Hello. How to change the size of the board (fixed to width: 100%, height: 100%) also show responsive in mobile (stretch or fit the board to the screen)?
![image](https://user-images.githubusercontent.com/65383156/90146334-2d1e1300-dd96-11ea-9045-fee9d388dcb1.png)

**Comment by lovasoa** [comment]
@ctoibvira : The board does not have a fixed width and height. It grows as users draw on it, making  it virtually (almost) infinite. You can pan and zoom on each device to display the part of the infinite board you are currently drawing on.
